version: "3.9"
services:
  web:
    build: ./parametrik
    environment:
      DJANGO_SETTINGS_MODULE: parametrik.settings
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
