version: "3.9"
services:
  web:
    build: ./parametrik
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: parametrik.settings_dev
    volumes:
      - ./parametrik:/code/
    ports:
      - "8000:8000"

  db:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
