# Generated by Django 3.2.3 on 2021-05-19 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drawings.point')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drawings.point')),
            ],
        ),
    ]
