# Generated by Django 3.2.3 on 2021-05-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0003_alter_projection_geometry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="end_point",
        ),
        migrations.RemoveField(
            model_name="line",
            name="start_point",
        ),
        migrations.DeleteModel(
            name="Point",
        ),
        migrations.DeleteModel(
            name="Line",
        ),
    ]
