# Generated by Django 3.2.3 on 2021-05-25 06:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_auto_20210523_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
