# Generated by Django 3.2.3 on 2021-05-25 20:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0005_alter_projection_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projection",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.CreateModel(
            name="ProjectionPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "projection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="drawings.projection",
                    ),
                ),
            ],
        ),
    ]
